// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Match {
    "Id": string;
    "FileName": string;
    "AbsolutePath": string;
    "MatchedLine": string;
    "TextBeforeMatch": string;
    "TextAfterMatch": string;
    "MatchedText": string;
    "ReplacementText": string;
    "Row": number;
    "Col": number;
    "Html": string;

    /** Creates a new Match instance. */
    constructor($$source: Partial<Match> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = "";
        }
        if (!("FileName" in $$source)) {
            this["FileName"] = "";
        }
        if (!("AbsolutePath" in $$source)) {
            this["AbsolutePath"] = "";
        }
        if (!("MatchedLine" in $$source)) {
            this["MatchedLine"] = "";
        }
        if (!("TextBeforeMatch" in $$source)) {
            this["TextBeforeMatch"] = "";
        }
        if (!("TextAfterMatch" in $$source)) {
            this["TextAfterMatch"] = "";
        }
        if (!("MatchedText" in $$source)) {
            this["MatchedText"] = "";
        }
        if (!("ReplacementText" in $$source)) {
            this["ReplacementText"] = "";
        }
        if (!("Row" in $$source)) {
            this["Row"] = 0;
        }
        if (!("Col" in $$source)) {
            this["Col"] = 0;
        }
        if (!("Html" in $$source)) {
            this["Html"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Match instance from a string or object.
     */
    static createFrom($$source: any = {}): Match {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Match($$parsedSource as Partial<Match>);
    }
}

export class MatchesOfFile {
    "Path": string;
    "Matches": Match[];

    /** Creates a new MatchesOfFile instance. */
    constructor($$source: Partial<MatchesOfFile> = {}) {
        if (!("Path" in $$source)) {
            this["Path"] = "";
        }
        if (!("Matches" in $$source)) {
            this["Matches"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MatchesOfFile instance from a string or object.
     */
    static createFrom($$source: any = {}): MatchesOfFile {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Matches" in $$parsedSource) {
            $$parsedSource["Matches"] = $$createField1_0($$parsedSource["Matches"]);
        }
        return new MatchesOfFile($$parsedSource as Partial<MatchesOfFile>);
    }
}

// Private type creation functions
const $$createType0 = Match.createFrom;
const $$createType1 = $Create.Array($$createType0);
