// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ClosePreview(winId: number): $CancellablePromise<void> {
    return $Call.ByID(2319571282, winId);
}

export function FindFiles(query: string): $CancellablePromise<($models.PickerResult | null)[]> {
    return $Call.ByID(2226073840, query).then(($result: any) => {
        return $$createType2($result);
    });
}

export function FindHelp(query: string): $CancellablePromise<($models.PickerResult | null)[]> {
    return $Call.ByID(3582785754, query).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetPreview(filepath: string, row: number, col: number): $CancellablePromise<void> {
    return $Call.ByID(1267762466, filepath, row, col);
}

export function OpenFile(path: string, row: number, col: number): $CancellablePromise<void> {
    return $Call.ByID(2355943308, path, row, col);
}

// Private type creation functions
const $$createType0 = $models.PickerResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
