// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as neovim$0 from "./neovim/models.js";

export function CreateQuickfixList(entries: (neovim$0.QuickfixEntry | null)[]): $CancellablePromise<void> {
    return $Call.ByID(96174031, entries);
}

export function GetReplacementText(matchedLine: string, searchTerm: string, replacementText: string, useRegex: boolean): $CancellablePromise<string> {
    return $Call.ByID(436416066, matchedLine, searchTerm, replacementText, useRegex);
}

/**
 * OnResize handles window resize events from the frontend
 */
export function OnResize(width: number, height: number): $CancellablePromise<void> {
    return $Call.ByID(1493062928, width, height);
}

export function Paste(text: string): $CancellablePromise<void> {
    return $Call.ByID(2887658624, text);
}

/**
 * ReadLocalImage decodes a base64-encoded local file path and returns it as a data URL.
 * This allows the frontend to load local images in both dev and production modes.
 */
export function ReadLocalImage(encoded: string): $CancellablePromise<string> {
    return $Call.ByID(4020051437, encoded);
}

/**
 * RequestState triggers emission of current state to frontend
 */
export function RequestState(): $CancellablePromise<void> {
    return $Call.ByID(3893193407);
}

export function SendKey(key: string, ctrl: boolean, alt: boolean, shift: boolean, keymapMode: string): $CancellablePromise<void> {
    return $Call.ByID(4136759966, key, ctrl, alt, shift, keymapMode);
}

export function SubstituteJump(): $CancellablePromise<void> {
    return $Call.ByID(598655329);
}
