// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "BufEnter": string;
            "cmdline_hide": any;
            "cmdline_pos": any;
            "cmdline_show": any;
            "completion-documentation": any;
            "completion-hide": any;
            "completion-select": number;
            "completion-show": any;
            "content-updated": any;
            "cursor-changed": any;
            "file-deleted": any;
            "file-explorer-close": any;
            "file-explorer-update": any;
            "file-replaced": any;
            "floating_window_closed": number;
            "floating_windows": any;
            "hide-live-rep": any;
            "hide-window": number;
            "highlight-css": string;
            "layout-updated": any;
            "mode-changed": string;
            "preview-window": any;
            "preview-window-closed": number;
            "show-file-explorer": any;
            "show-find-buffer-symbols": any;
            "show-find-files": any;
            "show-find-help": any;
            "show-find-references": any;
            "show_live_grep": any;
            "toast": any;
            "viewport_changed": any;
            "window_opened": any;
        }
    }
}
