// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {picker} from '../models';

export function GetLiveGrepOpts():Promise<picker.LiveGrepPickerState>;

export function GetNextPage():Promise<picker.LiveGrepPage>;

export function GetPrevPage():Promise<picker.LiveGrepPage>;

export function LiveGrep(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean,arg6:boolean,arg7:boolean):Promise<picker.LiveGrepPage>;
