// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLiveGrepOpts() {
  return window['go']['picker']['LiveGrepPicker']['GetLiveGrepOpts']();
}

export function GetNextPage() {
  return window['go']['picker']['LiveGrepPicker']['GetNextPage']();
}

export function GetPrevPage() {
  return window['go']['picker']['LiveGrepPicker']['GetPrevPage']();
}

export function LiveGrep(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['picker']['LiveGrepPicker']['LiveGrep'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}
