// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FindReferences(arg1) {
  return window['go']['picker']['LspReferencesPicker']['FindReferences'](arg1);
}
