// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {picker} from '../models';

export function FindReferences(arg1:string):Promise<Array<picker.PickerResult>>;
