// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {picker} from '../models';

export function ClosePreview(arg1:number):Promise<void>;

export function FindFiles(arg1:string):Promise<Array<picker.PickerResult>>;

export function FindHelp(arg1:string):Promise<Array<picker.PickerResult>>;

export function GetPreview(arg1:string,arg2:number,arg3:number):Promise<void>;

export function OpenFile(arg1:string,arg2:number,arg3:number):Promise<void>;
