// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClosePreview(arg1) {
  return window['go']['picker']['Picker']['ClosePreview'](arg1);
}

export function FindFiles(arg1) {
  return window['go']['picker']['Picker']['FindFiles'](arg1);
}

export function FindHelp(arg1) {
  return window['go']['picker']['Picker']['FindHelp'](arg1);
}

export function GetPreview(arg1, arg2, arg3) {
  return window['go']['picker']['Picker']['GetPreview'](arg1, arg2, arg3);
}

export function OpenFile(arg1, arg2, arg3) {
  return window['go']['picker']['Picker']['OpenFile'](arg1, arg2, arg3);
}
