// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetLiveGrepOpts(): $CancellablePromise<$models.LiveGrepPickerState> {
    return $Call.ByID(1936441004).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetNextPage(): $CancellablePromise<$models.LiveGrepPage> {
    return $Call.ByID(2863306542).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetPrevPage(): $CancellablePromise<$models.LiveGrepPage> {
    return $Call.ByID(3986421810).then(($result: any) => {
        return $$createType1($result);
    });
}

export function LiveGrep(searchTerm: string, dir: string, exclude: string, include: string, case_sensitive: boolean, regex: boolean, match_whole_word: boolean): $CancellablePromise<$models.LiveGrepPage> {
    return $Call.ByID(2537142730, searchTerm, dir, exclude, include, case_sensitive, regex, match_whole_word).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.LiveGrepPickerState.createFrom;
const $$createType1 = $models.LiveGrepPage.createFrom;
