// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as match$0 from "./match/models.js";

export class LiveGrepPage {
    "results": match$0.MatchesOfFile[];
    "pageIndex": number;
    "totalPages": number;
    "totalResults": number;
    "totalFiles": number;

    /** Creates a new LiveGrepPage instance. */
    constructor($$source: Partial<LiveGrepPage> = {}) {
        if (!("results" in $$source)) {
            this["results"] = [];
        }
        if (!("pageIndex" in $$source)) {
            this["pageIndex"] = 0;
        }
        if (!("totalPages" in $$source)) {
            this["totalPages"] = 0;
        }
        if (!("totalResults" in $$source)) {
            this["totalResults"] = 0;
        }
        if (!("totalFiles" in $$source)) {
            this["totalFiles"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LiveGrepPage instance from a string or object.
     */
    static createFrom($$source: any = {}): LiveGrepPage {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("results" in $$parsedSource) {
            $$parsedSource["results"] = $$createField0_0($$parsedSource["results"]);
        }
        return new LiveGrepPage($$parsedSource as Partial<LiveGrepPage>);
    }
}

export class LiveGrepPickerState {
    "searchTerm": string;
    "dir": string;
    "include": string;
    "exclude": string;
    "caseSensitive": boolean;
    "regex": boolean;
    "matchWholeWord": boolean;
    "totalResults": number;
    "totalFiles": number;

    /** Creates a new LiveGrepPickerState instance. */
    constructor($$source: Partial<LiveGrepPickerState> = {}) {
        if (!("searchTerm" in $$source)) {
            this["searchTerm"] = "";
        }
        if (!("dir" in $$source)) {
            this["dir"] = "";
        }
        if (!("include" in $$source)) {
            this["include"] = "";
        }
        if (!("exclude" in $$source)) {
            this["exclude"] = "";
        }
        if (!("caseSensitive" in $$source)) {
            this["caseSensitive"] = false;
        }
        if (!("regex" in $$source)) {
            this["regex"] = false;
        }
        if (!("matchWholeWord" in $$source)) {
            this["matchWholeWord"] = false;
        }
        if (!("totalResults" in $$source)) {
            this["totalResults"] = 0;
        }
        if (!("totalFiles" in $$source)) {
            this["totalFiles"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LiveGrepPickerState instance from a string or object.
     */
    static createFrom($$source: any = {}): LiveGrepPickerState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LiveGrepPickerState($$parsedSource as Partial<LiveGrepPickerState>);
    }
}

export class PickerResult {
    "filename": string;
    "relativePath": string;
    "absolutePath": string;
    "icon": string;
    "iconColor": string;
    "text": string;
    "row": number;
    "col": number;

    /** Creates a new PickerResult instance. */
    constructor($$source: Partial<PickerResult> = {}) {
        if (!("filename" in $$source)) {
            this["filename"] = "";
        }
        if (!("relativePath" in $$source)) {
            this["relativePath"] = "";
        }
        if (!("absolutePath" in $$source)) {
            this["absolutePath"] = "";
        }
        if (!("icon" in $$source)) {
            this["icon"] = "";
        }
        if (!("iconColor" in $$source)) {
            this["iconColor"] = "";
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("row" in $$source)) {
            this["row"] = 0;
        }
        if (!("col" in $$source)) {
            this["col"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PickerResult instance from a string or object.
     */
    static createFrom($$source: any = {}): PickerResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PickerResult($$parsedSource as Partial<PickerResult>);
    }
}

// Private type creation functions
const $$createType0 = match$0.MatchesOfFile.createFrom;
const $$createType1 = $Create.Array($$createType0);
