// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class QuickfixEntry {
    "filepath": string;
    "row": number;
    "col": number;
    "text": string;

    /** Creates a new QuickfixEntry instance. */
    constructor($$source: Partial<QuickfixEntry> = {}) {
        if (!("filepath" in $$source)) {
            this["filepath"] = "";
        }
        if (!("row" in $$source)) {
            this["row"] = 0;
        }
        if (!("col" in $$source)) {
            this["col"] = 0;
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QuickfixEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): QuickfixEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QuickfixEntry($$parsedSource as Partial<QuickfixEntry>);
    }
}
