// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Replace(arg1:main.RipgrepMatch,arg2:string,arg3:string):Promise<{[key: string]: Array<main.RipgrepMatch>}>;

export function Search(arg1:string,arg2:string,arg3:string,arg4:string):Promise<{[key: string]: Array<main.RipgrepMatch>}>;
