// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Replace(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Replace'](arg1, arg2, arg3, arg4);
}

export function ReplaceAll(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ReplaceAll'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function Search(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['Search'](arg1, arg2, arg3, arg4, arg5);
}
