// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Greet(arg1:string):Promise<string>;

export function Search(arg1:string,arg2:string,arg3:string,arg4:string):Promise<{[key: string]: Array<main.RipgrepMatch>}>;
