// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Replace(arg1:main.RipgrepMatch,arg2:string,arg3:string):Promise<void>;

export function ReplaceAll(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:Array<string>):Promise<void>;

export function Search(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<string>):Promise<{[key: string]: Array<main.RipgrepMatch>}>;
