import { OpenFile } from '$lib/wailsjs/go/picker/Picker.js';
// @ts-ignore - Generated by Wails v3
import * as App from '$lib/wailsjs/go/main/App.js';
import { Events, Call } from '@wailsio/runtime';
import {
	windowContentRowMap,
	layout,
	cursor,
	pickers,
	cmdline,
	nestedState,
	getFloatingWindows,
	setFloatingWindows,
	setFileExplorerState,
	setFileExplorerVisible,
	setFileExplorerConfirmPrompt,
	completion,
	setCompletionDocumentation
} from '$lib/state.svelte';
import { state as liveGrepState } from '$lib/picker/live-grep-results/results.service.svelte';

export function startListening() {
	window.addEventListener('resize', function () {
		Call.ByName('main.App.OnResize', window.innerWidth, window.innerHeight).catch((err) => {
			console.error('OnResize failed', err);
		});
	});

	// Request current state from backend (for late-connecting clients like tests)
	Call.ByName('main.App.RequestState').catch((err) => {
		console.error('RequestState failed', err);
	});

	Events.On('highlight-css', (ev) => {
		const css = ev.data;
		let el = document.getElementById('nvim-hl-style');
		if (!el) {
			el = document.createElement('style');
			el.id = 'nvim-hl-style';
			document.head.appendChild(el);
		}
		el.textContent = css;
	});
	Events.On('cmdline_show', (ev) => {
		const data = ev.data;
		cmdline.visible = true;
		cmdline.content = data.content;
		cmdline.pos = data.pos;
		cmdline.firstc = data.firstc;
		cmdline.prompt = data.prompt;
		cmdline.indent = data.indent;
	});

	Events.On('live-grep-prev-page', (ev) => {
		const data: any = ev.data;
		liveGrepState.results = data.updatedResults.GroupedMatches;
		liveGrepState.pageIndex = data.updatedPageIndex;
	});

	Events.On('live-grep-next-page', (ev) => {
		const data: any = ev.data;
		liveGrepState.results = data.updatedResults.GroupedMatches;
		liveGrepState.pageIndex = data.updatedPageIndex;
	});

	Events.On('live-grep-open-selected-match', (ev) => {
		const selectedMatch = liveGrepState.selectedMatch;
		if (!selectedMatch) return;
		OpenFile(selectedMatch.AbsolutePath, selectedMatch.Row, selectedMatch.Col);
	});

	Events.On('BufEnter', (ev) => {
		const filepath = ev.data;
		const activeWindow = layout.windows.find((win) => win.id === layout.activeWindowId);
		if (!activeWindow) return;
		activeWindow.filepath = filepath;
	});

	pickers.forEach((picker) => {
		Events.On(picker.showEvent, (ev) => {
			nestedState.activePicker = picker;
		});
	});

	Events.On('file-explorer-update', (ev) => {
		const state = ev.data;
		console.log(state)
		if (state && state.current) {
			setFileExplorerState(state);
			setFileExplorerVisible(true);
		}
	});

	Events.On('file-explorer-close', (_ev) => {
		setFileExplorerVisible(false);
		setFileExplorerState(null);
		setFileExplorerConfirmPrompt(null);
	});

	Events.On('file-explorer-confirm-prompt-show', (ev) => {
		const prompt = ev.data as App.FileExplorerConfirmPrompt;
		setFileExplorerConfirmPrompt(prompt);
	});

	Events.On('file-explorer-confirm-prompt-hide', (_ev) => {
		setFileExplorerConfirmPrompt(null);
	});

	Events.On('cmdline_pos', (ev) => {
		const data = ev.data;
		cmdline.pos = data.pos;
	});

	Events.On('cmdline_hide', (ev) => {
		cmdline.visible = false;
	});

	Events.On('layout-updated', (ev) => {
		const updatedLayout = ev.data;
		layout.cols = updatedLayout.cols;
		layout.rows = updatedLayout.rows;
		layout.activeWindowId = updatedLayout?.activeWindowId;
		layout.windows = updatedLayout.windows;
	});

	Events.On('content-updated', (ev) => {
		const data: any = ev.data;
		const winId = data.winId;
		const updatedContent = data.updatedContent;
		const existing = windowContentRowMap.get(winId);
		if (existing && existing.length === updatedContent.length) {
			for (let i = 0; i < updatedContent.length; i++) {
				if (
					!updatedContent[i].dirty &&
					existing[i] &&
					existing[i].index === updatedContent[i].index
				) {
					updatedContent[i] = existing[i];
				}
			}
		}
		windowContentRowMap.set(winId, updatedContent);
	});

	Events.On('cursor-changed', (ev) => {
		const e = ev.data;
		cursor.row = e.row;
		cursor.col = e.col;
		if (!layout) return;
		layout.activeWindowId = e.activeWindowId;
	});

	Events.On('mode-changed', (ev) => {
		const new_mode = ev.data;
		const activeWindow = layout.windows.find((win) => win.id == layout.activeWindowId);
		if (!activeWindow) return;
		activeWindow.mode = new_mode;
	});

	Events.On('floating_windows', (ev) => {
		const windows = ev.data;
		setFloatingWindows(windows);
	});

	Events.On('preview-window', (ev) => {
		const updatedPreviewWindow = ev.data;
		if (!nestedState.activePicker) return;
		nestedState.previewWindow = updatedPreviewWindow;
	});

	Events.On('preview-window-closed', (ev) => {
		const winId = ev.data;
		if (nestedState.previewWindow?.id !== winId) return;
		nestedState.previewWindow = undefined;
	});

	Events.On('floating_window_closed', (ev) => {
		const winId = ev.data;
		setFloatingWindows(getFloatingWindows().filter((win) => win.id !== winId));
	});

	Events.On('hide-window', (ev) => {
		const winId = ev.data;
		windowContentRowMap.delete(winId);
	});

	Events.On('completion-show', (ev) => {
		const state = ev.data;
		completion.visible = true;
		completion.items = state.items;
		completion.selectedIndex = state.selectedIndex;
		completion.col = state.col;
	});

	Events.On('completion-hide', (ev) => {
		completion.visible = false;
		completion.items = [];
		completion.selectedIndex = -1;
		setCompletionDocumentation(null);
	});

	Events.On('completion-select', (ev) => {
		const idx = ev.data;
		completion.selectedIndex = idx;
	});

	Events.On('completion-documentation', (ev) => {
		const doc = ev.data;
		setCompletionDocumentation(doc && (doc.text || doc.detail) ? doc : null);
	});
}
