import { OpenFile } from '@bindings/nvim-gui/picker/picker.js';
// @ts-ignore - Generated by Wails v3
import { App } from '@bindings/nvim-gui/index.js';
import { Events } from '@wailsio/runtime';
import { windowContentRowMap, cursor, pickers, cmdline, nestedState, getFloatingWindows, setFloatingWindows, completion, setCompletionDocumentation } from "$lib/state.svelte"
import {
  state as liveGrepState
} from '$lib/picker/live-grep-results/results.service.svelte';

let myWinId: number | null = null;
let myGridId: number | null = null;

export function setWindowContext(winId: number | null, gridId: number | null) {
  myWinId = winId;
  myGridId = gridId;
}

export function getWindowContext() {
  return { winId: myWinId, gridId: myGridId };
}

export async function init() {
}
export function startListening() {
  // Every window resizes its own grid
  window.addEventListener('resize', function () {
    if (myGridId !== null) {
      App.OnWindowResize(myGridId, window.innerWidth, window.innerHeight);
    }
  });

  // When this webview receives focus, tell Neovim to switch to the corresponding window
  let lastFocusedWinId: number | null = null;
  window.addEventListener('focus', function () {
    if (myWinId !== null && myWinId !== lastFocusedWinId) {
      lastFocusedWinId = myWinId;
      App.OnWindowFocus(myWinId);
    }
  });
  window.addEventListener('blur', function () {
    lastFocusedWinId = null;
  });

  // Request current state from backend (for late-connecting clients like tests)
  App.RequestState();

  Events.On('highlight-css', (ev) => {
    const css = ev.data;
    let el = document.getElementById('nvim-hl-style');
    if (!el) {
      el = document.createElement('style');
      el.id = 'nvim-hl-style';
      document.head.appendChild(el);
    }
    el.textContent = css;
  });
  Events.On('cmdline_show', (ev) => {
    // Only show cmdline on the active window
    if (myWinId !== null && cursor.activeWindowId !== myWinId) return;
    const data = ev.data;
    cmdline.visible = true;
    cmdline.content = data.content;
    cmdline.pos = data.pos;
    cmdline.firstc = data.firstc;
    cmdline.prompt = data.prompt;
    cmdline.indent = data.indent;
  });

  Events.On('live-grep-prev-page', (ev) => {
    const data: any = ev.data;
    liveGrepState.results = data.updatedResults.GroupedMatches;
    liveGrepState.pageIndex = data.updatedPageIndex;
  });

  Events.On('live-grep-next-page', (ev) => {
    const data: any = ev.data;
    liveGrepState.results = data.updatedResults.GroupedMatches;
    liveGrepState.pageIndex = data.updatedPageIndex;
  });

  Events.On('live-grep-open-selected-match', () => {
    const selectedMatch = liveGrepState.selectedMatch;
    if (!selectedMatch) return;
    OpenFile(selectedMatch.AbsolutePath, selectedMatch.Row, selectedMatch.Col);
  });

  Events.On('BufEnter', (ev) => {
    // BufEnter updates the filepath for this window
    // Only process if this is the active window
    if (myWinId !== null && cursor.activeWindowId === myWinId) {
      const filepath = ev.data;
      // Store filepath on the window's data — the page component reads it from data.window
      // Emit a custom event so the page can update
      window.dispatchEvent(new CustomEvent('nvim-bufenter', { detail: filepath }));
    }
  });

  pickers.forEach(picker => {
    Events.On(picker.showEvent, () => {
      // Only show picker on the active window
      if (myWinId !== null && cursor.activeWindowId !== myWinId) return;
      nestedState.activePicker = picker
    });
  })

  Events.On('cmdline_pos', (ev) => {
    if (myWinId !== null && cursor.activeWindowId !== myWinId) return;
    const data = ev.data;
    cmdline.pos = data.pos;
  });

  Events.On('cmdline_hide', () => {
    cmdline.visible = false;
  });

  Events.On('content-updated', (ev) => {
    const data: any = ev.data;
    const winId = data.winId;
    // Accept our own content + all floating window content (tagged by backend)
    // FloatingWindowContainer filters by anchorWindow for rendering
    if (myWinId !== null && winId !== myWinId && !data.floating) return;
    const updatedContent = data.updatedContent;
    const existing = windowContentRowMap.get(winId);
    if (existing && existing.length === updatedContent.length) {
      for (let i = 0; i < updatedContent.length; i++) {
        if (!updatedContent[i].dirty && existing[i] && existing[i].index === updatedContent[i].index) {
          updatedContent[i] = existing[i];
        }
      }
    }
    windowContentRowMap.set(winId, updatedContent);
  });

  Events.On('cursor-changed', (ev) => {
    const e = ev.data;
    cursor.row = e.row;
    cursor.col = e.col;
    cursor.activeWindowId = e.activeWindowId;
  });

  Events.On('mode-changed', (ev) => {
    const new_mode = ev.data;
    // Mode change is broadcast — dispatch custom event for the page to handle
    window.dispatchEvent(new CustomEvent('nvim-mode-changed', { detail: new_mode }));
  });

  Events.On('floating_windows', (ev) => {
    const windows = ev.data;
    console.log(windows)
    setFloatingWindows(windows);
  });

  Events.On('preview-window', (ev) => {
    if (myWinId !== null && cursor.activeWindowId !== myWinId) return;
    const updatedPreviewWindow = ev.data;
    if (!nestedState.activePicker) return
    nestedState.previewWindow = updatedPreviewWindow;
  })

  Events.On('preview-window-closed', (ev) => {
    const winId = ev.data;
    if (nestedState.previewWindow?.id !== winId) return
    nestedState.previewWindow = undefined;
  })

  Events.On('floating_window_closed', (ev) => {
    const winId = ev.data;
    setFloatingWindows(getFloatingWindows().filter((win) => win.id !== winId));
  });

  Events.On('hide-window', (ev) => {
    const winId = ev.data;
    windowContentRowMap.delete(winId);
  });

  Events.On('completion-show', (ev) => {
    // Only show completion on the active window
    if (myWinId !== null && cursor.activeWindowId !== myWinId) return;
    const state = ev.data;
    completion.visible = true;
    completion.items = state.items;
    completion.selectedIndex = state.selectedIndex;
    completion.col = state.col;
  });

  Events.On('completion-hide', () => {
    completion.visible = false;
    completion.items = [];
    completion.selectedIndex = -1;
    setCompletionDocumentation(null);
  });

  Events.On('completion-select', (ev) => {
    if (myWinId !== null && cursor.activeWindowId !== myWinId) return;
    const idx = ev.data;
    completion.selectedIndex = idx;
  });

  Events.On('completion-documentation', (ev) => {
    if (myWinId !== null && cursor.activeWindowId !== myWinId) return;
    const doc = ev.data;
    setCompletionDocumentation(doc && (doc.text || doc.detail) ? doc : null);
  });
}
