// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateQuickfixList(arg1) {
  return window['go']['main']['App']['CreateQuickfixList'](arg1);
}

export function GetReplacementText(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetReplacementText'](arg1, arg2, arg3, arg4);
}

export function ReadLocalImage(arg1) {
  return window['go']['main']['App']['ReadLocalImage'](arg1);
}

export function SendKey(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SendKey'](arg1, arg2, arg3, arg4, arg5);
}

export function SubstituteJump() {
  return window['go']['main']['App']['SubstituteJump']();
}
