// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {neovim} from '../models';

export function CreateQuickfixList(arg1:Array<neovim.QuickfixEntry>):Promise<void>;

export function GetReplacementText(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;

export function SendKey(arg1:string,arg2:boolean,arg3:boolean,arg4:boolean,arg5:string):Promise<void>;

export function SubstituteJump():Promise<void>;
