// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMatchesToQuickfixList() {
  return window['go']['main']['App']['AddMatchesToQuickfixList']();
}

export function GetAppState() {
  return window['go']['main']['App']['GetAppState']();
}

export function OpenMatch(arg1, arg2, arg3) {
  return window['go']['main']['App']['OpenMatch'](arg1, arg2, arg3);
}

export function SendKey(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendKey'](arg1, arg2, arg3, arg4);
}
