// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SendKey(arg1:string,arg2:boolean,arg3:boolean,arg4:boolean):Promise<void>;
