// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {picker} from '../models';

export function FindFiles(arg1:string):Promise<Array<picker.FindFilesResult>>;

export function GetLiveGrepOpts():Promise<picker.LiveGrepPickerState>;

export function GetNextPage():Promise<picker.SearchResult>;

export function GetPrevPage():Promise<picker.SearchResult>;

export function GetReplacementText(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;

export function LiveGrep(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean,arg6:boolean,arg7:boolean):Promise<picker.SearchResult>;

export function OpenFile(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SendKey(arg1:string,arg2:boolean,arg3:boolean,arg4:boolean,arg5:string):Promise<void>;

export function SubstituteJump():Promise<void>;
